version: "3"
services:
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
   container_name: elastic
   environment:
     - node.name=elastic
     - discovery.type=single-node
     - xpack.security.enabled=true
     - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
   volumes:
     - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
   ports:
     - 9200:9200
     - 9300:9300
   restart: always
   networks:
     - elk
     
  kibana:
   image: docker.elastic.co/kibana/kibana:7.6.0
   container_name: kibana
   environment:
     SERVER_NAME: kibana
     ELASTICSEARCH_URL: http://elasticsearch:9200
   depends_on:
     - logstash
   volumes:
     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
   ports:
     - 5601:5601
   restart: always
   networks:
     - elk
     
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/00-pipe.conf:/usr/share/logstash/pipline/
      - ./logstash/30-elastic.conf:/usr/share/logstash/pipline/
    environment:
      - "LS_JAVA_OPTS: -Xmx512m -Xms512m"
    ports:
      - 9600:9600
      - 5000:5000/tcp
      - 5000:5000/udp
    restart: always
    networks:
      - elk
      
networks:
  elk:
    driver: bridge 

